title: Fran Velasco

author: Fran Velasco

email: f@franvelas.co

description: >-
  Another personal site. Welcome to mine.

baseurl: ""

url: "https://franvelas.co"

twitter_username: efless

github_username:  franvelasco

theme: minima

plugins:
  - jekyll-feed
